PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS teams(id INTEGER PRIMARY KEY AUTOINCREMENT, fifa_code TEXT UNIQUE NOT NULL, name_ko TEXT NOT NULL, name_en TEXT NOT NULL, confederation TEXT NOT NULL, latitude REAL, longitude REAL, population INTEGER, gdp_per_capita REAL, updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS rankings(id INTEGER PRIMARY KEY AUTOINCREMENT, team_id INTEGER NOT NULL, release_date TEXT NOT NULL, rank INTEGER NOT NULL, points REAL NOT NULL, previous_rank INTEGER, source_url TEXT, source_hash TEXT, collected_at TEXT DEFAULT CURRENT_TIMESTAMP, UNIQUE(team_id, release_date), FOREIGN KEY(team_id) REFERENCES teams(id));
CREATE TABLE IF NOT EXISTS matches(id INTEGER PRIMARY KEY AUTOINCREMENT, external_id TEXT UNIQUE, match_date TEXT NOT NULL, home_team_id INTEGER NOT NULL, away_team_id INTEGER NOT NULL, home_score INTEGER NOT NULL, away_score INTEGER NOT NULL, competition TEXT NOT NULL, stage TEXT, importance REAL DEFAULT 10, neutral INTEGER DEFAULT 0, source_url TEXT, collected_at TEXT DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(home_team_id) REFERENCES teams(id), FOREIGN KEY(away_team_id) REFERENCES teams(id));
CREATE TABLE IF NOT EXISTS collection_jobs(id INTEGER PRIMARY KEY AUTOINCREMENT, job_type TEXT NOT NULL, status TEXT NOT NULL, started_at TEXT DEFAULT CURRENT_TIMESTAMP, finished_at TEXT, inserted_count INTEGER DEFAULT 0, warning_count INTEGER DEFAULT 0, message TEXT);
CREATE TABLE IF NOT EXISTS model_runs(id INTEGER PRIMARY KEY AUTOINCREMENT, model_name TEXT NOT NULL, network_type TEXT NOT NULL, formula TEXT NOT NULL, status TEXT NOT NULL, started_at TEXT DEFAULT CURRENT_TIMESTAMP, finished_at TEXT, aic REAL, bic REAL, converged INTEGER, result_json TEXT, diagnostics_json TEXT);
CREATE TABLE IF NOT EXISTS data_quality_issues(id INTEGER PRIMARY KEY AUTOINCREMENT, issue_type TEXT NOT NULL, severity TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT, message TEXT NOT NULL, resolved INTEGER DEFAULT 0, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_rankings_date ON rankings(release_date);
CREATE INDEX IF NOT EXISTS idx_matches_date ON matches(match_date);
