interface Env {
  DB: D1Database; ASSETS: Fetcher; AI: Ai;
  APP_NAME?: string; DATA_WINDOW_YEARS?: string;
  MATCH_CSV_URL?: string; WORLD_BANK_COUNTRY_URL?: string;
  WORLD_BANK_GDP_URL?: string; WORLD_BANK_POP_URL?: string;
  FREE_RANKING_CSV_URL?: string;
  GITHUB_OWNER?: string; GITHUB_REPO?: string; GITHUB_TOKEN?: string; ADMIN_TOKEN?: string;
}
type Obj=Record<string,any>;
const j=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store'}});
const iso=(d=new Date())=>d.toISOString().slice(0,10);
const yearsAgo=(y:number)=>{const d=new Date();d.setUTCFullYear(d.getUTCFullYear()-y);return iso(d)};
const auth=(r:Request,e:Env)=>!e.ADMIN_TOKEN||r.headers.get('authorization')===`Bearer ${e.ADMIN_TOKEN}`;
const norm=(s:any)=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,' ').trim();
const code=(s:any)=>String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8);
function parseCSV(text:string){
 const rows:string[][]=[];let row:string[]=[],cell='',q=false;
 for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(q){if(c==='"'&&n==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}
 if(cell||row.length){row.push(cell);rows.push(row)} if(!rows.length)return[];const h=rows.shift()!.map(x=>x.trim());return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??'').trim()])));
}
async function fetchText(url:string){const r=await fetch(url,{headers:{accept:'text/csv,application/json;q=0.9,*/*;q=0.8','user-agent':'FIFA-Network-Lab/5.0'}});const t=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status} ${url}: ${t.slice(0,180)}`);return t}
async function fetchJSON(url:string){return JSON.parse(await fetchText(url))}
const cfg=(e:Env)=>({
 matchUrl:e.MATCH_CSV_URL||'https://raw.githubusercontent.com/martj42/international_results/master/results.csv',
 countriesUrl:e.WORLD_BANK_COUNTRY_URL||'https://api.worldbank.org/v2/country?format=json&per_page=400',
 gdpUrl:e.WORLD_BANK_GDP_URL||'https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.CD?format=json&per_page=20000&date=2022:2026',
 popUrl:e.WORLD_BANK_POP_URL||'https://api.worldbank.org/v2/country/all/indicator/SP.POP.TOTL?format=json&per_page=20000&date=2022:2026',
 rankingUrl:e.FREE_RANKING_CSV_URL||'', rankingMode:e.FREE_RANKING_CSV_URL?'community-csv':'manual-csv'
});
async function snapshot(e:Env,name:string,url:string,status:number,count=0,note=''){await e.DB.prepare('INSERT INTO source_snapshots(source_name,source_url,status,row_count,note) VALUES(?,?,?,?,?)').bind(name,url,status,count,note).run()}
async function upsertTeam(e:Env,c:string,name:string,conf='UNK',lat:null|number=null,lon:null|number=null){c=code(c);if(!c||!name)return null;await e.DB.prepare(`INSERT INTO teams(fifa_code,name_ko,name_en,confederation,latitude,longitude) VALUES(?,?,?,?,?,?) ON CONFLICT(fifa_code) DO UPDATE SET name_en=excluded.name_en,confederation=CASE WHEN excluded.confederation='UNK' THEN teams.confederation ELSE excluded.confederation END,latitude=COALESCE(excluded.latitude,teams.latitude),longitude=COALESCE(excluded.longitude,teams.longitude),updated_at=CURRENT_TIMESTAMP`).bind(c,name,name,conf,lat,lon).run();const t=await e.DB.prepare('SELECT id,fifa_code,name_en FROM teams WHERE fifa_code=?').bind(c).first<any>();if(t)await e.DB.prepare(`INSERT INTO team_aliases(alias,team_id,source) VALUES(?,?,?) ON CONFLICT(alias) DO UPDATE SET team_id=excluded.team_id`).bind(norm(name),t.id,'worldbank').run();return t}
function confFromRegion(r:string){return ({'East Asia & Pacific':'AFC','Europe & Central Asia':'UEFA','Latin America & Caribbean':'CONMEBOL/CONCACAF','Middle East, North Africa, Afghanistan & Pakistan':'AFC/CAF','North America':'CONCACAF','South Asia':'AFC','Sub-Saharan Africa':'CAF'} as Obj)[r]||'UNK'}
async function collectCountries(e:Env){const c=cfg(e);try{const d=await fetchJSON(c.countriesUrl);const rows=Array.isArray(d?.[1])?d[1]:[];let n=0;for(const x of rows){if(!x?.id||x.region?.id==='NA')continue;const t=await upsertTeam(e,x.id,x.name,confFromRegion(x.region?.value||''),Number(x.latitude)||null,Number(x.longitude)||null);if(t)n++}await snapshot(e,'world-bank-countries',c.countriesUrl,200,n);return n}catch(err){await snapshot(e,'world-bank-countries',c.countriesUrl,500,0,String(err));throw err}}
async function latestIndicators(e:Env,url:string,col:'population'|'gdp_per_capita'){const d=await fetchJSON(url);const rows=Array.isArray(d?.[1])?d[1]:[];const seen=new Set<string>();let n=0;for(const x of rows){const cc=code(x.countryiso3code);if(!cc||seen.has(cc)||x.value==null)continue;seen.add(cc);const r=await e.DB.prepare(`UPDATE teams SET ${col}=?,updated_at=CURRENT_TIMESTAMP WHERE fifa_code=?`).bind(Number(x.value),cc).run();n+=r.meta.changes||0}await snapshot(e,`world-bank-${col}`,url,200,n);return n}
async function aliases(e:Env){const q=await e.DB.prepare(`SELECT a.alias,t.id,t.fifa_code,t.name_en FROM team_aliases a JOIN teams t ON t.id=a.team_id UNION SELECT lower(name_en),id,fifa_code,name_en FROM teams`).all<any>();return new Map(q.results.map(x=>[norm(x.alias),x]))}
async function collectMatches(e:Env){const c=cfg(e),text=await fetchText(c.matchUrl),rows=parseCSV(text),map=await aliases(e),floor=yearsAgo(Number(e.DATA_WINDOW_YEARS||4));let ins=0,skip=0;for(const r of rows){if(String(r.date)<floor)continue;let h=map.get(norm(r.home_team)),a=map.get(norm(r.away_team));if(!h){h=await upsertTeam(e,`X${btoa(unescape(encodeURIComponent(norm(r.home_team)))).replace(/[^A-Z0-9]/gi,'').slice(0,6)}`,r.home_team);if(h){map.set(norm(r.home_team),h);await e.DB.prepare('INSERT OR REPLACE INTO team_aliases(alias,team_id,source) VALUES(?,?,?)').bind(norm(r.home_team),h.id,'match-csv').run()}}if(!a){a=await upsertTeam(e,`X${btoa(unescape(encodeURIComponent(norm(r.away_team)))).replace(/[^A-Z0-9]/gi,'').slice(0,6)}`,r.away_team);if(a){map.set(norm(r.away_team),a);await e.DB.prepare('INSERT OR REPLACE INTO team_aliases(alias,team_id,source) VALUES(?,?,?)').bind(norm(r.away_team),a.id,'match-csv').run()}}if(!h||!a){skip++;continue}const hs=Number(r.home_score),as=Number(r.away_score);if(!Number.isFinite(hs)||!Number.isFinite(as)){skip++;continue}const id=`martj42:${r.date}:${norm(r.home_team)}:${norm(r.away_team)}`;await e.DB.prepare(`INSERT INTO matches(external_id,match_date,home_team_id,away_team_id,home_score,away_score,competition,neutral,source_url) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(external_id) DO UPDATE SET home_score=excluded.home_score,away_score=excluded.away_score,competition=excluded.competition,neutral=excluded.neutral,collected_at=CURRENT_TIMESTAMP`).bind(id,r.date,h.id,a.id,hs,as,r.tournament||'International',String(r.neutral).toLowerCase()==='true'?1:0,c.matchUrl).run();ins++}await snapshot(e,'international-results',c.matchUrl,200,ins,`skipped=${skip}`);return{inserted:ins,skipped:skip,total:rows.length}}
async function collectRankings(e:Env){const url=cfg(e).rankingUrl;if(!url)return{inserted:0,warning:'무료 랭킹 CSV URL이 설정되지 않았습니다. 데이터 화면에서 FIFA CSV를 업로드하십시오.'};const rows=parseCSV(await fetchText(url));let ins=0,skip=0;for(const r of rows){const name=r.country_full||r.country||r.team||r.name;const cc=code(r.country_abrv||r.country_code||r.iso3||r.code);const date=String(r.rank_date||r.date||r.release_date||'').slice(0,10);const rank=Number(r.rank),points=Number(r.total_points||r.points);if(!name||!date||!Number.isFinite(rank)||!Number.isFinite(points)){skip++;continue}const t=await upsertTeam(e,cc||`R${rank}`,name,r.confederation||'UNK');if(!t){skip++;continue}await e.DB.prepare(`INSERT INTO rankings(team_id,release_date,rank,points,previous_rank,source_url) VALUES(?,?,?,?,?,?) ON CONFLICT(team_id,release_date) DO UPDATE SET rank=excluded.rank,points=excluded.points,previous_rank=excluded.previous_rank,source_url=excluded.source_url,collected_at=CURRENT_TIMESTAMP`).bind(t.id,date,rank,points,Number(r.previous_rank)||null,url).run();ins++}await snapshot(e,'ranking-csv',url,200,ins,`skipped=${skip}`);return{inserted:ins,skipped:skip}}
async function collect(e:Env){const id=(await e.DB.prepare(`INSERT INTO collection_jobs(job_type,status,message) VALUES('free_sources','running','started') RETURNING id`).first<any>())?.id;const messages:string[]=[];let inserted=0,warnings=0;try{const c=await collectCountries(e);inserted+=c;messages.push(`국가 ${c}`);for(const [u,col] of [[cfg(e).gdpUrl,'gdp_per_capita'],[cfg(e).popUrl,'population']] as const){try{const n=await latestIndicators(e,u,col);messages.push(`${col} ${n}`)}catch(x){warnings++;messages.push(`${col} 경고: ${x}`)}}const m=await collectMatches(e);inserted+=m.inserted;messages.push(`경기 ${m.inserted}, 제외 ${m.skipped}`);try{const r=await collectRankings(e);inserted+=r.inserted;messages.push(r.warning||`랭킹 ${r.inserted}`);if(r.warning)warnings++}catch(x){warnings++;messages.push(`랭킹 경고: ${x}`)}await e.DB.prepare(`UPDATE collection_jobs SET status='success',finished_at=CURRENT_TIMESTAMP,inserted_count=?,warning_count=?,message=? WHERE id=?`).bind(inserted,warnings,messages.join(' | '),id).run();return{ok:true,provider:'free-open-sources',inserted,warnings,messages}}catch(x){await e.DB.prepare(`UPDATE collection_jobs SET status='failed',finished_at=CURRENT_TIMESTAMP,message=? WHERE id=?`).bind(String(x),id).run();throw x}}
async function dashboard(e:Env){const one=async(s:string)=>(await e.DB.prepare(s).first<any>())||{};const [t,m,r,i,runs,jobs]=await Promise.all([one('SELECT COUNT(*) n FROM teams'),one('SELECT COUNT(*) n FROM matches'),one('SELECT COUNT(*) n FROM rankings'),one('SELECT COUNT(*) n FROM data_quality_issues WHERE resolved=0'),e.DB.prepare('SELECT * FROM model_runs ORDER BY id DESC LIMIT 5').all(),e.DB.prepare('SELECT * FROM collection_jobs ORDER BY id DESC LIMIT 5').all()]);return{teams:t.n||0,matches:m.n||0,rankings:r.n||0,issues:i.n||0,runs:runs.results,jobs:jobs.results,provider:cfg(e)}}
async function network(e:Env,u:URL){const from=u.searchParams.get('from')||yearsAgo(Number(e.DATA_WINDOW_YEARS||4)),to=u.searchParams.get('to')||iso(),type=u.searchParams.get('type')||'match';const q=await e.DB.prepare(`SELECT m.*,h.fifa_code hcode,h.name_en hname,h.confederation hconf,a.fifa_code acode,a.name_en aname,a.confederation aconf FROM matches m JOIN teams h ON h.id=m.home_team_id JOIN teams a ON a.id=m.away_team_id WHERE m.match_date BETWEEN ? AND ?`).bind(from,to).all<any>();const ns=new Map(),ls=new Map();for(const r of q.results){ns.set(r.hcode,{id:r.hcode,label:r.hname,group:r.hconf});ns.set(r.acode,{id:r.acode,label:r.aname,group:r.aconf});let s=r.hcode,t=r.acode;if(type==='win'){if(r.home_score===r.away_score)continue;if(r.home_score<r.away_score)[s,t]=[t,s]}const k=type==='match'?[s,t].sort().join('|'):`${s}|${t}`;const x=ls.get(k)||{source:s,target:t,value:0};x.value++;ls.set(k,x)}return{nodes:[...ns.values()],links:[...ls.values()],meta:{from,to,type,matches:q.results.length}}}
async function quality(e:Env){const d=await e.DB.prepare(`SELECT match_date,home_team_id,away_team_id,COUNT(*) n FROM matches GROUP BY match_date,home_team_id,away_team_id HAVING n>1`).all();const v=await e.DB.prepare(`SELECT id FROM matches WHERE home_score<0 OR away_score<0 OR home_team_id=away_team_id`).all();return{score:Math.max(0,100-d.results.length*5-v.results.length*10),duplicates:d.results,invalid:v.results}}
async function importRows(r:Request,e:Env){const b=await r.json() as any,rows=Array.isArray(b.rows)?b.rows:[];let n=0;if(b.kind==='rankings'){for(const x of rows){const t=await upsertTeam(e,x.fifa_code||x.code,x.name||x.country,x.confederation||'UNK');if(!t)continue;await e.DB.prepare(`INSERT INTO rankings(team_id,release_date,rank,points,previous_rank,source_url) VALUES(?,?,?,?,?,?) ON CONFLICT(team_id,release_date) DO UPDATE SET rank=excluded.rank,points=excluded.points,previous_rank=excluded.previous_rank`).bind(t.id,x.release_date||x.date,Number(x.rank),Number(x.points),Number(x.previous_rank)||null,'manual-upload').run();n++}}return{ok:true,inserted:n}}
export default {async fetch(r:Request,e:Env){try{const u=new URL(r.url),p=u.pathname;if(p==='/api/health')return j({ok:true,app:e.APP_NAME||'FIFA Network Lab',version:'5.0.0',time:new Date().toISOString()});if(p==='/api/provider')return j({provider:'free-open-sources',...cfg(e),hasApiKey:true});if(p==='/api/provider/test'){const c=cfg(e),tests=[];for(const [name,url] of Object.entries(c)){if(typeof url!=='string'||!url.startsWith('http'))continue;try{const res=await fetch(url,{method:'HEAD'});tests.push({name,url,ok:res.ok,status:res.status})}catch(x){tests.push({name,url,ok:false,error:String(x)})}}return j({ok:tests.every((x:any)=>x.ok),results:tests})}if(p==='/api/dashboard')return j(await dashboard(e));if(p==='/api/network')return j(await network(e,u));if(p==='/api/rankings'){const q=await e.DB.prepare(`SELECT r.release_date,r.rank,r.points,r.previous_rank,t.fifa_code,t.name_ko,t.name_en,t.confederation FROM rankings r JOIN teams t ON t.id=r.team_id ORDER BY r.release_date DESC,r.rank LIMIT 1000`).all();return j(q.results)}if(p==='/api/quality')return j(await quality(e));if(p==='/api/collect'&&r.method==='POST'){if(!auth(r,e))return j({error:'unauthorized'},401);return j(await collect(e))}if(p==='/api/import'&&r.method==='POST'){if(!auth(r,e))return j({error:'unauthorized'},401);return j(await importRows(r,e))}if(p==='/api/export'){const [t,m,rr]=await Promise.all([e.DB.prepare('SELECT * FROM teams').all(),e.DB.prepare('SELECT * FROM matches').all(),e.DB.prepare('SELECT * FROM rankings').all()]);return j({metadata:{generated_at:new Date().toISOString(),sources:cfg(e)},teams:t.results,matches:m.results,rankings:rr.results})}if(p==='/api/models'&&r.method==='POST'){const b=await r.json() as any;const x=await e.DB.prepare(`INSERT INTO model_runs(model_name,network_type,formula,status) VALUES(?,?,?,'queued') RETURNING id`).bind(b.name||'ERGM',b.networkType||'win',b.formula||'network ~ edges').first<any>();return j({ok:true,runId:x.id,note:'모형 요청을 저장했습니다. GitHub Actions R 분석 연결 시 실행됩니다.'})}return e.ASSETS.fetch(r)}catch(x){return j({ok:false,error:x instanceof Error?x.message:String(x)},500)}},async scheduled(_c:ScheduledController,e:Env){await collect(e)}};
