interface Env {
  DB:D1Database; ASSETS:Fetcher; AI:Ai;
  APP_NAME?:string; DATA_WINDOW_YEARS?:string; BATCH_STATEMENTS?:string;
  MATCH_CSV_URL?:string; WORLD_BANK_COUNTRY_URL?:string; WORLD_BANK_GDP_URL?:string;
  WORLD_BANK_POP_URL?:string; FREE_RANKING_CSV_URL?:string; ADMIN_TOKEN?:string;
  GITHUB_TOKEN?:string; GITHUB_OWNER?:string; GITHUB_REPO?:string; ANALYSIS_API_TOKEN?:string; PUBLIC_BASE_URL?:string;
}
type Obj=Record<string,any>;
type Task={kind:'countries'|'gdp'|'population'|'matches'|'rankings'; month?:string; label:string};
const VERSION='7.0.0';
const j=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store'}});
const iso=(d=new Date())=>d.toISOString().slice(0,10);
const auth=(r:Request,e:Env)=>!e.ADMIN_TOKEN||r.headers.get('authorization')===`Bearer ${e.ADMIN_TOKEN}`;
const norm=(s:any)=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,' ').trim();
const code=(s:any)=>String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,8);
const cfg=(e:Env)=>({
  matchUrl:e.MATCH_CSV_URL||'https://raw.githubusercontent.com/martj42/international_results/master/results.csv',
  countriesUrl:e.WORLD_BANK_COUNTRY_URL||'https://api.worldbank.org/v2/country?format=json&per_page=400',
  gdpUrl:e.WORLD_BANK_GDP_URL||'https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.CD?format=json&per_page=20000&date=2022:2026',
  popUrl:e.WORLD_BANK_POP_URL||'https://api.worldbank.org/v2/country/all/indicator/SP.POP.TOTL?format=json&per_page=20000&date=2022:2026',
  rankingUrl:e.FREE_RANKING_CSV_URL||'https://raw.githubusercontent.com/Dato-Futbol/fifa-ranking/refs/heads/master/ranking_fifa_historical.csv'
});
function parseCSV(text:string){const rows:string[][]=[];let row:string[]=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(q){if(c==='"'&&n==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell);rows.push(row)}if(!rows.length)return[];const h=rows.shift()!.map(x=>x.trim());return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(h.map((k,i)=>[k,(r[i]??'').trim()])))}
async function fetchText(url:string){const r=await fetch(url,{headers:{accept:'text/csv,application/json;q=0.9,*/*;q=0.8','user-agent':`FIFA-Network-Lab/${VERSION}`}});const t=await r.text();if(!r.ok)throw new Error(`HTTP ${r.status} ${url}: ${t.slice(0,180)}`);return t}
async function fetchJSON(url:string){return JSON.parse(await fetchText(url))}
function months(years:number){const now=new Date(),start=new Date(Date.UTC(now.getUTCFullYear()-years,now.getUTCMonth(),1)),out:string[]=[];for(const d=new Date(start);d<=now;d.setUTCMonth(d.getUTCMonth()+1))out.push(d.toISOString().slice(0,7));return out}
function plan(e:Env){const ms=months(Number(e.DATA_WINDOW_YEARS||4));const tasks:Task[]=[{kind:'countries',label:'국가 메타데이터'},{kind:'gdp',label:'1인당 GDP'},{kind:'population',label:'인구'}];for(const m of ms)tasks.push({kind:'matches',month:m,label:`경기 ${m}`});if(cfg(e).rankingUrl)for(const m of ms)tasks.push({kind:'rankings',month:m,label:`랭킹 ${m}`});return tasks}
async function state(e:Env,key:string,def=''){return (await e.DB.prepare('SELECT value FROM collection_state WHERE key=?').bind(key).first<any>())?.value??def}
async function setState(e:Env,key:string,value:string){await e.DB.prepare(`INSERT INTO collection_state(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP`).bind(key,value).run()}
function chunk<T>(a:T[],n:number){const out:T[][]=[];for(let i=0;i<a.length;i+=n)out.push(a.slice(i,i+n));return out}
async function batches(e:Env,stmts:D1PreparedStatement[]){const size=Math.max(10,Math.min(100,Number(e.BATCH_STATEMENTS||75)));let calls=0;for(const c of chunk(stmts,size)){await e.DB.batch(c);calls++}return calls}
async function snap(e:Env,name:string,url:string,status:number,count=0,note=''){await e.DB.prepare('INSERT INTO source_snapshots(source_name,source_url,status,row_count,note) VALUES(?,?,?,?,?)').bind(name,url,status,count,note).run()}
function confFromRegion(r:string){return ({'East Asia & Pacific':'AFC','Europe & Central Asia':'UEFA','Latin America & Caribbean':'CONMEBOL/CONCACAF','Middle East, North Africa, Afghanistan & Pakistan':'AFC/CAF','North America':'CONCACAF','South Asia':'AFC','Sub-Saharan Africa':'CAF'} as Obj)[r]||'UNK'}
async function teamMaps(e:Env){const q=await e.DB.prepare(`SELECT t.id,t.fifa_code,t.name_en,a.alias FROM teams t LEFT JOIN team_aliases a ON a.team_id=t.id`).all<any>();const byCode=new Map<string,any>(),byAlias=new Map<string,any>();for(const x of q.results){byCode.set(x.fifa_code,x);byAlias.set(norm(x.name_en),x);if(x.alias)byAlias.set(norm(x.alias),x)}return{byCode,byAlias}}
async function taskCountries(e:Env){const u=cfg(e).countriesUrl,d=await fetchJSON(u),rows=(Array.isArray(d?.[1])?d[1]:[]).filter((x:any)=>x?.id&&x.region?.id!=='NA');const up=rows.map((x:any)=>e.DB.prepare(`INSERT INTO teams(fifa_code,name_ko,name_en,confederation,latitude,longitude) VALUES(?,?,?,?,?,?) ON CONFLICT(fifa_code) DO UPDATE SET name_en=excluded.name_en,confederation=excluded.confederation,latitude=excluded.latitude,longitude=excluded.longitude,updated_at=CURRENT_TIMESTAMP`).bind(code(x.id),x.name,x.name,confFromRegion(x.region?.value||''),Number(x.latitude)||null,Number(x.longitude)||null));let calls=await batches(e,up);const map=await e.DB.prepare('SELECT id,name_en FROM teams').all<any>();calls++;calls+=await batches(e,map.results.map(x=>e.DB.prepare(`INSERT INTO team_aliases(alias,team_id,source) VALUES(?,?,?) ON CONFLICT(alias) DO UPDATE SET team_id=excluded.team_id`).bind(norm(x.name_en),x.id,'worldbank')));await snap(e,'world-bank-countries',u,200,rows.length,`db_calls=${calls}`);return{inserted:rows.length,dbCalls:calls,externalCalls:1}}
async function taskIndicator(e:Env,kind:'gdp'|'population'){const u=kind==='gdp'?cfg(e).gdpUrl:cfg(e).popUrl,col=kind==='gdp'?'gdp_per_capita':'population',d=await fetchJSON(u),rows=Array.isArray(d?.[1])?d[1]:[],seen=new Set<string>(),stmts:D1PreparedStatement[]=[];for(const x of rows){const cc=code(x.countryiso3code);if(!cc||seen.has(cc)||x.value==null)continue;seen.add(cc);stmts.push(e.DB.prepare(`UPDATE teams SET ${col}=?,updated_at=CURRENT_TIMESTAMP WHERE fifa_code=?`).bind(Number(x.value),cc))}const calls=await batches(e,stmts);await snap(e,`world-bank-${col}`,u,200,stmts.length,`db_calls=${calls}`);return{inserted:stmts.length,dbCalls:calls,externalCalls:1}}
function syntheticCode(name:string){let h=2166136261;for(const c of norm(name)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return`X${Math.abs(h>>>0).toString(36).toUpperCase().slice(0,6)}`}
async function ensureNames(e:Env,names:string[]){let maps=await teamMaps(e),missing=[...new Set(names)].filter(n=>!maps.byAlias.has(norm(n)));let calls=1;if(missing.length){calls+=await batches(e,missing.map(n=>e.DB.prepare(`INSERT INTO teams(fifa_code,name_ko,name_en,confederation) VALUES(?,?,?,'UNK') ON CONFLICT(fifa_code) DO UPDATE SET name_en=excluded.name_en`).bind(syntheticCode(n),n,n)));maps=await teamMaps(e);calls++;calls+=await batches(e,missing.map(n=>{const t=maps.byCode.get(syntheticCode(n));return e.DB.prepare(`INSERT INTO team_aliases(alias,team_id,source) VALUES(?,?,?) ON CONFLICT(alias) DO UPDATE SET team_id=excluded.team_id`).bind(norm(n),t.id,'match-csv')}));maps=await teamMaps(e);calls++}return{...maps,calls}}
async function taskMatches(e:Env,month:string){const u=cfg(e).matchUrl,rows=parseCSV(await fetchText(u)).filter(r=>String(r.date||'').slice(0,7)===month),names=rows.flatMap(r=>[r.home_team,r.away_team]).filter(Boolean),maps=await ensureNames(e,names),stmts:D1PreparedStatement[]=[];let skip=0;for(const r of rows){const h=maps.byAlias.get(norm(r.home_team)),a=maps.byAlias.get(norm(r.away_team)),hs=Number(r.home_score),as=Number(r.away_score);if(!h||!a||!Number.isFinite(hs)||!Number.isFinite(as)){skip++;continue}const id=`martj42:${r.date}:${norm(r.home_team)}:${norm(r.away_team)}`;stmts.push(e.DB.prepare(`INSERT INTO matches(external_id,match_date,home_team_id,away_team_id,home_score,away_score,competition,neutral,source_url) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(external_id) DO UPDATE SET home_score=excluded.home_score,away_score=excluded.away_score,competition=excluded.competition,neutral=excluded.neutral,collected_at=CURRENT_TIMESTAMP`).bind(id,r.date,h.id,a.id,hs,as,r.tournament||'International',String(r.neutral).toLowerCase()==='true'?1:0,u))}const bc=await batches(e,stmts),calls=maps.calls+bc;await snap(e,'international-results',u,200,stmts.length,`month=${month};skipped=${skip};db_calls=${calls}`);return{inserted:stmts.length,skipped:skip,dbCalls:calls,externalCalls:1}}
async function taskRankings(e:Env,month:string){const u=cfg(e).rankingUrl;if(!u)return{inserted:0,skipped:0,dbCalls:0,externalCalls:0,warning:'랭킹 URL 미설정'};const rows=parseCSV(await fetchText(u)).filter(r=>String(r.date||r.rank_date||r.release_date||'').slice(0,7)===month);const names=rows.map(r=>r.team||r.country_full||r.country||r.name).filter(Boolean),maps=await ensureNames(e,names),group=new Map<string,Obj[]>();for(const r of rows){const date=String(r.date||r.rank_date||r.release_date).slice(0,10);if(!group.has(date))group.set(date,[]);group.get(date)!.push(r)}const stmts:D1PreparedStatement[]=[];let skip=0;for(const [date,list] of group){const sorted=[...list].sort((a,b)=>Number(b.total_points||b.points)-Number(a.total_points||a.points));for(let i=0;i<sorted.length;i++){const r=sorted[i],name=r.team||r.country_full||r.country||r.name,cc=code(r.team_short||r.team_code||r.country_abrv||r.country_code||r.iso3||r.code),t=maps.byCode.get(cc)||maps.byAlias.get(norm(name)),points=Number(r.total_points||r.points),rank=Number(r.rank)||i+1;if(!t||!date||!Number.isFinite(points)){skip++;continue}stmts.push(e.DB.prepare(`INSERT INTO rankings(team_id,release_date,rank,points,previous_rank,source_url) VALUES(?,?,?,?,?,?) ON CONFLICT(team_id,release_date) DO UPDATE SET rank=excluded.rank,points=excluded.points,previous_rank=excluded.previous_rank,source_url=excluded.source_url,collected_at=CURRENT_TIMESTAMP`).bind(t.id,date,rank,points,Number(r.previous_rank)||null,u))}}const bc=await batches(e,stmts),calls=maps.calls+bc;await snap(e,'ranking-csv',u,200,stmts.length,`month=${month};skipped=${skip};db_calls=${calls}`);return{inserted:stmts.length,skipped:skip,dbCalls:calls,externalCalls:1}}
async function progress(e:Env){const tasks=plan(e),cursor=Math.max(0,Number(await state(e,'v6_cursor','0'))||0),done=Math.min(cursor,tasks.length),next=tasks[done]||null;return{version:VERSION,total:tasks.length,completed:done,remaining:Math.max(0,tasks.length-done),percent:tasks.length?Math.round(done/tasks.length*100):100,next,finished:done>=tasks.length,windowMonths:months(Number(e.DATA_WINDOW_YEARS||4)).length,limitStrategy:'one task per invocation; batched D1 statements'}}
async function collectOne(e:Env,reset=false){if(reset)await setState(e,'v6_cursor','0');const tasks=plan(e),cursor=Math.max(0,Number(await state(e,'v6_cursor','0'))||0);if(cursor>=tasks.length)return{ok:true,finished:true,progress:await progress(e),message:'최근 4년 배치 수집이 완료되었습니다.'};const task=tasks[cursor],jid=(await e.DB.prepare(`INSERT INTO collection_jobs(job_type,status,message) VALUES('v6_batch','running',?) RETURNING id`).bind(task.label).first<any>())?.id;try{let result:any;if(task.kind==='countries')result=await taskCountries(e);else if(task.kind==='gdp'||task.kind==='population')result=await taskIndicator(e,task.kind);else if(task.kind==='matches')result=await taskMatches(e,task.month!);else result=await taskRankings(e,task.month!);await setState(e,'v6_cursor',String(cursor+1));await e.DB.prepare(`UPDATE collection_jobs SET status='success',finished_at=CURRENT_TIMESTAMP,inserted_count=?,warning_count=?,message=? WHERE id=?`).bind(result.inserted||0,result.warning?1:0,JSON.stringify({task,...result}),jid).run();return{ok:true,task,index:cursor+1,...result,progress:await progress(e)}}catch(x){await e.DB.prepare(`UPDATE collection_jobs SET status='failed',finished_at=CURRENT_TIMESTAMP,message=? WHERE id=?`).bind(String(x),jid).run();throw x}}
async function dashboard(e:Env){const one=async(s:string)=>(await e.DB.prepare(s).first<any>())||{};const [t,m,r,i,runs,jobs,p]=await Promise.all([one('SELECT COUNT(*) n FROM teams'),one('SELECT COUNT(*) n FROM matches'),one('SELECT COUNT(*) n FROM rankings'),one('SELECT COUNT(*) n FROM data_quality_issues WHERE resolved=0'),e.DB.prepare('SELECT * FROM model_runs ORDER BY id DESC LIMIT 5').all(),e.DB.prepare('SELECT * FROM collection_jobs ORDER BY id DESC LIMIT 5').all(),progress(e)]);return{teams:t.n||0,matches:m.n||0,rankings:r.n||0,issues:i.n||0,runs:runs.results,jobs:jobs.results,provider:cfg(e),progress:p}}
async function network(e:Env,u:URL){const from=u.searchParams.get('from')||months(Number(e.DATA_WINDOW_YEARS||4))[0]+'-01',to=u.searchParams.get('to')||iso(),type=u.searchParams.get('type')||'match';const q=await e.DB.prepare(`SELECT m.*,h.fifa_code hcode,h.name_en hname,h.confederation hconf,a.fifa_code acode,a.name_en aname,a.confederation aconf FROM matches m JOIN teams h ON h.id=m.home_team_id JOIN teams a ON a.id=m.away_team_id WHERE m.match_date BETWEEN ? AND ?`).bind(from,to).all<any>();const ns=new Map(),ls=new Map();for(const r of q.results){ns.set(r.hcode,{id:r.hcode,label:r.hname,group:r.hconf});ns.set(r.acode,{id:r.acode,label:r.aname,group:r.aconf});let s=r.hcode,t=r.acode;if(type==='win'){if(r.home_score===r.away_score)continue;if(r.home_score<r.away_score)[s,t]=[t,s]}const k=type==='match'?[s,t].sort().join('|'):`${s}|${t}`,x=ls.get(k)||{source:s,target:t,value:0};x.value++;ls.set(k,x)}return{nodes:[...ns.values()],links:[...ls.values()],meta:{from,to,type,matches:q.results.length}}}
async function quality(e:Env){const d=await e.DB.prepare(`SELECT match_date,home_team_id,away_team_id,COUNT(*) n FROM matches GROUP BY match_date,home_team_id,away_team_id HAVING n>1`).all(),v=await e.DB.prepare(`SELECT id FROM matches WHERE home_score<0 OR away_score<0 OR home_team_id=away_team_id`).all();return{score:Math.max(0,100-d.results.length*5-v.results.length*10),duplicates:d.results,invalid:v.results}}
async function importRows(r:Request,e:Env){const b=await r.json() as any,rows=Array.isArray(b.rows)?b.rows:[],stmts:D1PreparedStatement[]=[];if(b.kind==='rankings'){const maps=await ensureNames(e,rows.map((x:any)=>x.name||x.country).filter(Boolean));for(const x of rows){const t=maps.byCode.get(code(x.fifa_code||x.code))||maps.byAlias.get(norm(x.name||x.country));if(!t)continue;stmts.push(e.DB.prepare(`INSERT INTO rankings(team_id,release_date,rank,points,previous_rank,source_url) VALUES(?,?,?,?,?,?) ON CONFLICT(team_id,release_date) DO UPDATE SET rank=excluded.rank,points=excluded.points,previous_rank=excluded.previous_rank`).bind(t.id,x.release_date||x.date,Number(x.rank),Number(x.points),Number(x.previous_rank)||null,'manual-upload'))}}await batches(e,stmts);return{ok:true,inserted:stmts.length}}

const analysisAuth=(r:Request,e:Env)=>Boolean(e.ANALYSIS_API_TOKEN)&&r.headers.get('authorization')===`Bearer ${e.ANALYSIS_API_TOKEN}`;
async function triggerGithub(e:Env,runId:number){
  if(!e.GITHUB_TOKEN||!e.GITHUB_OWNER||!e.GITHUB_REPO)throw new Error('GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO 설정이 필요합니다.');
  const response=await fetch(`https://api.github.com/repos/${e.GITHUB_OWNER}/${e.GITHUB_REPO}/dispatches`,{method:'POST',headers:{authorization:`Bearer ${e.GITHUB_TOKEN}`,accept:'application/vnd.github+json','content-type':'application/json','user-agent':'fifa-network-lab','x-github-api-version':'2022-11-28'},body:JSON.stringify({event_type:'run-ergm',client_payload:{run_id:String(runId),base_url:e.PUBLIC_BASE_URL||''}})});
  if(!response.ok)throw new Error(`GitHub dispatch 실패 HTTP ${response.status}: ${(await response.text()).slice(0,300)}`);
}
export default {
 async fetch(r:Request,e:Env){try{const u=new URL(r.url),p=u.pathname;if(p==='/api/health')return j({ok:true,app:e.APP_NAME||'FIFA Network Lab',version:VERSION,time:new Date().toISOString()});if(p==='/api/provider')return j({provider:'free-open-sources-v7',...cfg(e),progress:await progress(e),apiKeyRequired:false});if(p==='/api/provider/test'){const c=cfg(e),tests=[];for(const [name,url] of Object.entries(c)){if(typeof url!=='string'||!url.startsWith('http'))continue;try{const res=await fetch(url,{headers:{Range:'bytes=0-128'}});tests.push({name,url,ok:res.ok,status:res.status})}catch(x){tests.push({name,url,ok:false,error:String(x)})}}return j({ok:tests.every((x:any)=>x.ok),results:tests})}if(p==='/api/dashboard')return j(await dashboard(e));if(p==='/api/progress')return j(await progress(e));if(p==='/api/network')return j(await network(e,u));if(p==='/api/rankings'){const q=await e.DB.prepare(`SELECT r.release_date,r.rank,r.points,r.previous_rank,t.fifa_code,t.name_ko,t.name_en,t.confederation FROM rankings r JOIN teams t ON t.id=r.team_id ORDER BY r.release_date DESC,r.rank LIMIT 1000`).all();return j(q.results)}if(p==='/api/quality')return j(await quality(e));if(p==='/api/collect'&&r.method==='POST'){if(!auth(r,e))return j({error:'unauthorized'},401);const b=await r.json().catch(()=>({})) as any;return j(await collectOne(e,Boolean(b.reset)))}if(p==='/api/import'&&r.method==='POST'){if(!auth(r,e))return j({error:'unauthorized'},401);return j(await importRows(r,e))}if(p==='/api/export'){const [t,m,rr]=await Promise.all([e.DB.prepare('SELECT * FROM teams').all(),e.DB.prepare('SELECT * FROM matches').all(),e.DB.prepare('SELECT * FROM rankings').all()]);return j({metadata:{generated_at:new Date().toISOString(),version:VERSION,sources:cfg(e),progress:await progress(e)},teams:t.results,matches:m.results,rankings:rr.results})}if(p==='/api/models'&&r.method==='GET'){const id=Number(u.searchParams.get('id')||0);if(id){const x=await e.DB.prepare('SELECT * FROM model_runs WHERE id=?').bind(id).first<any>();return x?j(x):j({error:'model run not found'},404)}const q=await e.DB.prepare('SELECT * FROM model_runs ORDER BY id DESC LIMIT 50').all();return j(q.results)}
if(p==='/api/models'&&r.method==='POST'){if(!auth(r,e))return j({error:'unauthorized'},401);const b=await r.json() as any,x=await e.DB.prepare(`INSERT INTO model_runs(model_name,network_type,formula,status) VALUES(?,?,?,'queued') RETURNING id`).bind(b.name||'ERGM',b.networkType||'win',b.formula||'network ~ edges').first<any>();if(!x?.id)return j({error:'모형 요청 저장 실패'},500);try{await triggerGithub(e,x.id);await e.DB.prepare(`UPDATE model_runs SET status='dispatched' WHERE id=?`).bind(x.id).run();return j({ok:true,runId:x.id,status:'dispatched',note:'GitHub Actions R 분석을 요청했습니다.'})}catch(err){await e.DB.prepare(`UPDATE model_runs SET status='dispatch_failed',diagnostics_json=? WHERE id=?`).bind(JSON.stringify({error:String(err)}),x.id).run();return j({ok:false,runId:x.id,status:'dispatch_failed',error:err instanceof Error?err.message:String(err)},502)}}
if(p==='/api/model-input'&&r.method==='GET'){if(!analysisAuth(r,e))return j({error:'unauthorized'},401);const runId=Number(u.searchParams.get('run_id'));const run=await e.DB.prepare('SELECT * FROM model_runs WHERE id=?').bind(runId).first<any>();if(!run)return j({error:'model run not found'},404);await e.DB.prepare(`UPDATE model_runs SET status='running',started_at=CURRENT_TIMESTAMP WHERE id=?`).bind(runId).run();const [teams,matches,rankings]=await Promise.all([e.DB.prepare('SELECT * FROM teams ORDER BY id').all(),e.DB.prepare('SELECT * FROM matches ORDER BY match_date,id').all(),e.DB.prepare('SELECT r.* FROM rankings r JOIN (SELECT team_id,MAX(release_date) d FROM rankings GROUP BY team_id) z ON z.team_id=r.team_id AND z.d=r.release_date').all()]);return j({run,teams:teams.results,matches:matches.results,rankings:rankings.results,metadata:{version:VERSION,generated_at:new Date().toISOString()}})}
if(p==='/api/model-results'&&r.method==='POST'){if(!analysisAuth(r,e))return j({error:'unauthorized'},401);const b=await r.json() as any,runId=Number(b.run_id);if(!runId)return j({error:'run_id required'},400);await e.DB.prepare(`UPDATE model_runs SET status=?,finished_at=CURRENT_TIMESTAMP,aic=?,bic=?,converged=?,result_json=?,diagnostics_json=? WHERE id=?`).bind(b.status||'completed',b.aic??null,b.bic??null,b.converged?1:0,JSON.stringify(b.result||{}),JSON.stringify(b.diagnostics||{}),runId).run();return j({ok:true,runId})}
return e.ASSETS.fetch(r)}catch(x){return j({ok:false,error:x instanceof Error?x.message:String(x)},500)}},
 async scheduled(_c:ScheduledController,e:Env){await collectOne(e)}
};
